In [3]:
import pandas as pd
c_data=pd.read_csv("census.csv")
c_data.head()

,73,Highschoolgraduate,Widowed,Female,Nonfiler,1700.09,Notinuniverse,United-States,Native-BornintheUnitedStates,0
0,58,Somecollegebutnodegree,Divorced,Male,Headofhousehold,1053.55,Notinuniverse,United-States,Native-BornintheUnitedStates,52
1,18,10thgrade,Nevermarried,Female,Nonfiler,991.95,Notinuniverse,Vietnam,Foreignborn-NotacitizenofUS,0
2,9,Children,Nevermarried,Female,Nonfiler,1758.14,Bothparentspresent,United-States,Native-BornintheUnitedStates,0
3,10,Children,Nevermarried,Female,Nonfiler,1069.16,Bothparentspresent,United-States,Native-BornintheUnitedStates,0
4,48,Somecollegebutnodegree,Married-civilianspousepresent,Female,Jointbothunder65,162.61,Notinuniverse,United-States,Native-BornintheUnitedStates,52

In [4]:
c_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   73                            1999 non-null   int64
 1   Highschoolgraduate            1999 non-null   object
 2   Widowed                       1999 non-null   object
 3   Female                        1999 non-null   object
 4   Nonfiler                      1999 non-null   object
 5   1700.09                       1999 non-null   float64
 6   Notinuniverse                 1999 non-null   object
 7   United-States                 1999 non-null   object
 8   Native-BornintheUnitedStates  1999 non-null   object
 9   0                             1999 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 156.3+ KB

In [6]:
c_data.columns = [
    "Age",
    "Education",
    "Marital_Status",
    "Gender",
    "Tax_Status",
    "Income",
    "Employment_Status",
    "Country",
    "Citizenship",
    "Weeks_Worked"
] 
c_data.head()

,Age,Education,Marital_Status,Gender,Tax_Status,Income,Employment_Status,Country,Citizenship,Weeks_Worked
0,58,Somecollegebutnodegree,Divorced,Male,Headofhousehold,1053.55,Notinuniverse,United-States,Native-BornintheUnitedStates,52
1,18,10thgrade,Nevermarried,Female,Nonfiler,991.95,Notinuniverse,Vietnam,Foreignborn-NotacitizenofUS,0
2,9,Children,Nevermarried,Female,Nonfiler,1758.14,Bothparentspresent,United-States,Native-BornintheUnitedStates,0
3,10,Children,Nevermarried,Female,Nonfiler,1069.16,Bothparentspresent,United-States,Native-BornintheUnitedStates,0
4,48,Somecollegebutnodegree,Married-civilianspousepresent,Female,Jointbothunder65,162.61,Notinuniverse,United-States,Native-BornintheUnitedStates,52

In [8]:
ed_distribution=c_data["Education"].value_counts()
ed_distribution

Education
Highschoolgraduate                   482
Children                             452
Somecollegebutnodegree               295
Bachelorsdegree(BAABBS)              206
10thgrade                             81
7thand8thgrade                        81
Mastersdegree(MAMSMEngMEdMSWMBA)      68
11thgrade                             68
Associatesdegree-occup/vocational     56
9thgrade                              56
Associatesdegree-academicprogram      50
5thor6thgrade                         21
Profschooldegree(MDDDSDVMLLBJD)       20
12thgradenodiploma                    18
1st2nd3rdor4thgrade                   16
Doctoratedegree(PhDEdD)               15
Lessthan1stgrade                      14
Name: count, dtype: int64

In [ ]:
import matplotlib.pyplot as plt
ed_dic